version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - environment/production.env
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - environment/production.env